// ======= TRADUCTIONS (Français / العربية / English) =======
const translations = {
    fr: {
        // Header
        subtitle: "Restaurant – Café – Terrasse",
        ambience_title: "Notre Ambiance",
        breakfast_title: "LE PETIT-DÉJEUNER",
        ftor_chamali: "Ftor Chamali",
        ftor_chamali_desc: "Khobz • Zayt zitoun • Zayt beldi • Jben • Zaitoun • Atay / Café • Bayd omelette",
        ftor_fransi: "Ftor Fransi",
        ftor_fransi_desc: "Baguette / Croissant • Beurre • Confiture • Jben • Café au lait / Chocolat chaud • Jus",
        omelettes: "Omelettes",
        omelette_fromage: "Omelette Fromage",
        omelette_fromage_desc: "(Oeuf + Fromage + Pain)",
        omelette_thon: "Omelette Thon",
        omelette_thon_desc: "(Oeuf + Thon + Fromage + Pain)",
        omelette_mix: "Omelette Mix",
        omelette_mix_desc: "(Oeuf + Fromage + Thon + Légumes)",
        omelette_ziz: "Omelette Ziz",
        omelette_ziz_desc: "(Oeuf + Fromage + Thon + Charcuterie)",
        omelette_speciale: "Omelette Spéciale",
        omelette_speciale_desc: "(... + Charcuterie + Légumes)",
        // Categories
        panini: "PANINI",
        sandwich: "SANDWICH",
        tacos: "TACOS",
        burger: "BURGER",
        pizza: "PIZZA",
        four_snack: "FOUR & SNACK",
        pastichio: "Pastichio",
        gratin_sigar: "Gratin & Sigar",
        salade: "SALADE",
        plat: "PLAT",
        couscous: "COUSCOUS",
        glaces: "LES GLACES",
        // Items
        dinde: "Dinde",
        viande_hachee: "Viande hachée",
        mix: "Mix",
        royal: "Royal",
        fruit_de_mer: "Fruit de mer",
        kabda: "Kabda",
        cordon_bleu: "Cordon bleu",
        chicken: "Chicken",
        american: "Américan",
        cheeseburger: "Cheeseburger",
        margarita: "Margarita",
        fromages_4: "4 Fromages",
        dinde_fume: "Dinde fumé",
        thon: "Thon",
        saison_4: "4 Saison",
        calzone: "Calzone",
        gratin_mix: "Gratin Mix",
        gratin_royal: "Gratin Royal / Ziz",
        sigar_mix: "Sigar Mix",
        sigar_royal: "Sigar Royal / Ziz",
        marocaine: "Marocaine",
        micsican: "Micsican",
        sizar: "Sizar",
        chaf: "Chaf",
        brochette_dinde: "Brochette dinde",
        escalope: "Escalope",
        emince_poulet: "Emincé de poulet",
        // Couscous / Tagine
        tagine_info: "TAGINE :",
        tagine_desc: "Sur commande",
        couscous_info: "COUSCOUS :",
        couscous_desc: "Le Spécial du",
        vendredi: "Vendredi",
        vendredi_badge: "Vendredi Uniquement",
        couscous_poulet: "Couscous poulet",
        couscous_viande: "Couscous viande",
        couscous_tfaya: "Couscous tfaya",
        couscous_mix: "Couscous mix",
        lben: "Lben",
        // Glaces
        fraise: "Fraise",
        nougat: "Nougat",
        chocolat: "Chocolat",
        pistache: "Pistache",
        vanille: "Vanille",
        la_boule: "3 Boules :",
        // About
        about_title: "Mieux nous connaître",
        about_text: "<strong>Café ZIZ</strong> est l'un des restaurants et cafés les plus réputés à <strong>Azilal</strong>, connu pour la qualité de ses plats et son service raffiné 👑.",
        about_features_title: "⭐ Ce qui distingue Café ZIZ :",
        feature_1: "Produits frais & Haute qualité",
        feature_2: "Prix accessibles à tous",
        feature_3: "Espace agréable et confortable",
        feature_4: "Service rapide et respectueux",
        feature_5: "Idéal pour familles et jeunes",
        about_vision_title: "🎯 Notre Objectif :",
        about_vision_text: "Offrir une expérience exceptionnelle alliant :<br><strong>Goût – Qualité – Confort – Confiance</strong>",
        // Maps
        maps_title: "Notre Localisation",
        maps_desc: "Café & Restaurant Ziz, La meilleure adresse à Azilal.",
        // Video
        video_title: "Découvrez Café ZIZ",
        video_desc: "Plongez dans l'ambiance unique de notre espace.",
        // Galerie
        gallery_btn: "Voir la Galerie Photos",
        gallery_subtitle: "Découvrez notre espace et nos délices",
        back_menu: "Retour au Menu",
        // Footer
        slogan: "Qualité – Goût – Service",
        // Nav
        nav_ftour: "Ftour",
        nav_fastfood: "Fast Food",
        nav_plats: "Plats",
        nav_boissons: "Boissons",
        nav_desserts: "Desserts",
        // Drinks
        boissons_chaudes: "BOISSONS CHAUDES",
        boissons_froid: "BOISSONS FROID",
        les_jus: "LES JUS",
        espresso: "Espresso",
        cappuccino: "Cappuccino",
        cafe_nes_nes: "Café nes nes",
        espresso_au_lait: "Espresso au lait",
        cafe_noir: "Café noir",
        cafe_creme: "Café crème",
        chocolat_chaud: "Chocolat chaud",
        red_bull: "Red bull",
        eau_minerale_33cl: "Eau minérale 33cl",
        soda: "Soda",
        eau_minerale_05l: "Eau minérale 0.5L",
        eau_minerale_15l: "Eau minérale 1.5L",
        jus_ananas: "Jus d'Ananas",
        jus_fraise: "Jus de fraise",
        jus_mangue: "Jus de mangue",
        jus_citron: "Jus de citron",
        jus_peche: "Jus de pêche",
        jus_kiwi: "Jus de kiwi",
        jus_orange: "Jus d'orange",
        jus_pomme: "Jus de pomme",
        jus_banane: "Jus de banane",
        jus_avocat: "Jus d'avocat",
        panache: "Panaché",
        jus_mojito: "Jus mojito",
        jus_carotte: "Jus de carotte",
    },

    ar: {
        subtitle: "مطعم – مقهى – تراس",
        ambience_title: "أجواؤنا ✨",
        breakfast_title: "وجبات الإفطار",
        ftor_chamali: "فطور شمالي",
        ftor_chamali_desc: "خبز • زيت زيتون • زيت بلدي • جبن • زيتون • أتاي / قهوة • بيض أومليت",
        ftor_fransi: "فطور فرنسي",
        ftor_fransi_desc: "باغيت / كرواسون • زبدة • مربى • جبن • قهوة بالحليب / شوكولا ساخن • عصير",
        omelettes: "أومليت",
        omelette_fromage: "أومليت فروماج",
        omelette_fromage_desc: "(بيض + جبن + خبز)",
        omelette_thon: "أومليت تون",
        omelette_thon_desc: "(بيض + تونة + جبن + خبز)",
        omelette_mix: "أومليت ميكس",
        omelette_mix_desc: "(بيض + جبن + تونة + خضار)",
        omelette_ziz: "أومليت زيز",
        omelette_ziz_desc: "(بيض + جبن + تونة + شاركوتيري)",
        omelette_speciale: "أومليت سبيسيال",
        omelette_speciale_desc: "(... + شاركوتيري + خضار)",
        panini: "بانيني",
        sandwich: "ساندويش",
        tacos: "تاكوس",
        burger: "برغر",
        pizza: "بيتزا",
        four_snack: "فور & سناك",
        pastichio: "باستيشو",
        gratin_sigar: "غراتان & سيغار",
        salade: "سلطة",
        plat: "طبق",
        couscous: "كسكس",
        glaces: "المثلجات",
        dinde: "ديند",
        viande_hachee: "لحم مفروم",
        mix: "ميكس",
        royal: "رويال",
        fruit_de_mer: "فواكه البحر",
        kabda: "كبدة",
        cordon_bleu: "كوردون بلو",
        chicken: "دجاج",
        american: "أمريكان",
        cheeseburger: "تشيزبرغر",
        margarita: "مرغريتا",
        fromages_4: "4 أجبان",
        dinde_fume: "ديند مدخن",
        thon: "تونة",
        saison_4: "4 فصول",
        calzone: "كالزوني",
        gratin_mix: "غراتان ميكس",
        gratin_royal: "غراتان رويال / زيز",
        sigar_mix: "سيغار ميكس",
        sigar_royal: "سيغار رويال / زيز",
        marocaine: "مغربية",
        micsican: "مكسيكية",
        sizar: "سيزار",
        chaf: "شاف",
        brochette_dinde: "بروشيت ديند",
        escalope: "إسكالوب",
        emince_poulet: "إيمانسي دجاج",
        tagine_info: "طاجين :",
        tagine_desc: "على الطلب",
        couscous_info: "كسكس :",
        couscous_desc: "سبيسيال ديال",
        vendredi: "الجمعة",
        vendredi_badge: "الجمعة فقط",
        couscous_poulet: "كسكس دجاج",
        couscous_viande: "كسكس لحم",
        couscous_tfaya: "كسكس تفاية",
        couscous_mix: "كسكس ميكس",
        lben: "لبن",
        fraise: "فراولة",
        nougat: "نوغات",
        chocolat: "شوكولا",
        pistache: "فستق",
        vanille: "فانيلا",
        la_boule: "3 كرات :",
        about_title: "تعرف علينا أكثر",
        about_text: "<strong>كافي زيز</strong> واحد من أشهر المطاعم والمقاهي في <strong>أزيلال</strong>، معروف بجودة أطباقه وخدمته الراقية 👑.",
        about_features_title: "⭐ ما يميز كافي زيز :",
        feature_1: "منتجات طازجة & جودة عالية",
        feature_2: "أسعار مناسبة للجميع",
        feature_3: "مكان مريح وأنيق",
        feature_4: "خدمة سريعة ومحترمة",
        feature_5: "مناسب للعائلات والشباب",
        about_vision_title: "🎯 هدفنا :",
        about_vision_text: "تقديم تجربة استثنائية تجمع بين :<br><strong>المذاق – الجودة – الراحة – الثقة</strong>",
        maps_title: "موقعنا",
        maps_desc: "مقهى ومطعم زيز، أفضل مكان في أزيلال.",
        video_title: "اكتشف كافي زيز",
        video_desc: "انغمس في الأجواء الفريدة لمكاننا.",
        gallery_btn: "معرض الصور",
        gallery_subtitle: "اكتشف مساحتنا وأطباقنا اللذيذة",
        back_menu: "العودة إلى القائمة",
        slogan: "الجودة – المذاق – الخدمة",
        // Nav
        nav_ftour: "فطور",
        nav_fastfood: "أكلات سريعة",
        nav_plats: "أطباق",
        nav_boissons: "مشروبات",
        nav_desserts: "حلويات",
        // Drinks
        boissons_chaudes: "مشروبات ساخنة",
        boissons_froid: "مشروبات باردة",
        les_jus: "العصائر",
        espresso: "إسبريسو",
        cappuccino: "كابوتشينو",
        cafe_nes_nes: "قهوة نص نص",
        espresso_au_lait: "إسبريسو بالحليب",
        cafe_noir: "قهوة سوداء",
        cafe_creme: "قهوة كريمة",
        chocolat_chaud: "شوكولاتة ساخنة",
        red_bull: "ريد بول",
        eau_minerale_33cl: "ماء معدني 33 مل",
        soda: "صودا",
        eau_minerale_05l: "ماء معدني 0.5 لتر",
        eau_minerale_15l: "ماء معدني 1.5 لتر",
        jus_ananas: "عصير الأناناس",
        jus_fraise: "عصير الفراولة",
        jus_mangue: "عصير المانجو",
        jus_citron: "عصير الليمون",
        jus_peche: "عصير الخوخ",
        jus_kiwi: "عصير الكيوي",
        jus_orange: "عصير البرتقال",
        jus_pomme: "عصير التفاح",
        jus_banane: "عصير الموز",
        jus_avocat: "عصير لافوكا",
        panache: "باناشي",
        jus_mojito: "عصير موهيتو",
        jus_carotte: "عصير الجزر",
    },

    en: {
        subtitle: "Restaurant – Café – Terrace",
        ambience_title: "Our Atmosphere",
        breakfast_title: "BREAKFAST",
        ftor_chamali: "Moroccan Breakfast",
        ftor_chamali_desc: "Bread • Olive oil • Local oil • Cheese • Olives • Tea / Coffee • Egg omelette",
        ftor_fransi: "French Breakfast",
        ftor_fransi_desc: "Baguette / Croissant • Butter • Jam • Cheese • Café au lait / Hot chocolate • Juice",
        omelettes: "Omelettes",
        omelette_fromage: "Cheese Omelette",
        omelette_fromage_desc: "(Egg + Cheese + Bread)",
        omelette_thon: "Tuna Omelette",
        omelette_thon_desc: "(Egg + Tuna + Cheese + Bread)",
        omelette_mix: "Mix Omelette",
        omelette_mix_desc: "(Egg + Cheese + Tuna + Vegetables)",
        omelette_ziz: "Ziz Omelette",
        omelette_ziz_desc: "(Egg + Cheese + Tuna + Charcuterie)",
        omelette_speciale: "Special Omelette",
        omelette_speciale_desc: "(... + Charcuterie + Vegetables)",
        panini: "PANINI",
        sandwich: "SANDWICH",
        tacos: "TACOS",
        burger: "BURGER",
        pizza: "PIZZA",
        four_snack: "OVEN & SNACK",
        pastichio: "Pastichio",
        gratin_sigar: "Gratin & Sigar",
        salade: "SALAD",
        plat: "MAIN DISH",
        couscous: "COUSCOUS",
        glaces: "ICE CREAM",
        dinde: "Turkey",
        viande_hachee: "Minced meat",
        mix: "Mix",
        royal: "Royal",
        fruit_de_mer: "Seafood",
        kabda: "Liver",
        cordon_bleu: "Cordon bleu",
        chicken: "Chicken",
        american: "American",
        cheeseburger: "Cheeseburger",
        margarita: "Margarita",
        fromages_4: "4 Cheeses",
        dinde_fume: "Smoked turkey",
        thon: "Tuna",
        saison_4: "4 Seasons",
        calzone: "Calzone",
        gratin_mix: "Gratin Mix",
        gratin_royal: "Gratin Royal / Ziz",
        sigar_mix: "Sigar Mix",
        sigar_royal: "Sigar Royal / Ziz",
        marocaine: "Moroccan",
        micsican: "Mexican",
        sizar: "Caesar",
        chaf: "Chef",
        brochette_dinde: "Turkey skewer",
        escalope: "Escalope",
        emince_poulet: "Chicken Emincé",
        tagine_info: "TAGINE:",
        tagine_desc: "On order",
        couscous_info: "COUSCOUS:",
        couscous_desc: "The Special of",
        vendredi: "Friday",
        vendredi_badge: "Friday Only",
        couscous_poulet: "Chicken couscous",
        couscous_viande: "Meat couscous",
        couscous_tfaya: "Tfaya couscous",
        couscous_mix: "Mix couscous",
        lben: "Buttermilk",
        fraise: "Strawberry",
        nougat: "Nougat",
        chocolat: "Chocolate",
        pistache: "Pistachio",
        vanille: "Vanilla",
        la_boule: "3 Scoops:",
        about_title: "Get to Know Us",
        about_text: "<strong>Café ZIZ</strong> is one of the most renowned restaurants and cafés in <strong>Azilal</strong>, known for the quality of its dishes and refined service 👑.",
        about_features_title: "⭐ What makes Café ZIZ special:",
        feature_1: "Fresh products & High quality",
        feature_2: "Affordable prices for everyone",
        feature_3: "Pleasant and comfortable space",
        feature_4: "Fast and respectful service",
        feature_5: "Ideal for families and young people",
        about_vision_title: "🎯 Our Goal:",
        about_vision_text: "Offering an exceptional experience combining:<br><strong>Taste – Quality – Comfort – Trust</strong>",
        maps_title: "Our Location",
        maps_desc: "Café & Restaurant Ziz, The best place in Azilal.",
        video_title: "Discover Café ZIZ",
        video_desc: "Immerse yourself in the unique atmosphere of our space.",
        gallery_btn: "View Photo Gallery",
        gallery_subtitle: "Discover our space and delicious dishes",
        back_menu: "Back to Menu",
        slogan: "Quality – Taste – Service",
        // Nav
        nav_ftour: "Breakfast",
        nav_fastfood: "Fast Food",
        nav_plats: "Plats",
        nav_boissons: "Drinks",
        nav_desserts: "Desserts",
        // Drinks
        boissons_chaudes: "HOT DRINKS",
        boissons_froid: "COLD DRINKS",
        les_jus: "JUICES",
        espresso: "Espresso",
        cappuccino: "Cappuccino",
        cafe_nes_nes: "Coffee Nes Nes",
        espresso_au_lait: "Espresso with Milk",
        cafe_noir: "Black Coffee",
        cafe_creme: "Cream Coffee",
        chocolat_chaud: "Hot Chocolate",
        red_bull: "Red Bull",
        eau_minerale_33cl: "Mineral Water 33cl",
        soda: "Soda",
        eau_minerale_05l: "Mineral Water 0.5L",
        eau_minerale_15l: "Mineral Water 1.5L",
        jus_ananas: "Pineapple Juice",
        jus_fraise: "Strawberry Juice",
        jus_mangue: "Mango Juice",
        jus_citron: "Lemon Juice",
        jus_peche: "Peach Juice",
        jus_kiwi: "Kiwi Juice",
        jus_orange: "Orange Juice",
        jus_pomme: "Apple Juice",
        jus_banane: "Banana Juice",
        jus_avocat: "Avocado Juice",
        panache: "Mixed Fruit Juice",
        jus_mojito: "Mojito Juice",
        jus_carotte: "Carrot Juice",
    }
};

// ======= MOTEUR DE TRADUCTION =======
let currentLang = 'fr';

function setLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('cafeZizLang', lang); // Save user preference
    const t = translations[lang];

    // Update all elements with data-i18n attribute
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (t[key] !== undefined) {
            if (el.hasAttribute('data-i18n-html')) {
                el.innerHTML = t[key];
            } else {
                el.textContent = t[key];
            }
        }
    });

    // Handle RTL for Arabic
    const menuBorder = document.querySelector('.menu-border');
    const html = document.documentElement;
    if (lang === 'ar') {
        html.setAttribute('dir', 'rtl');
        html.setAttribute('lang', 'ar');
        menuBorder.style.direction = 'rtl';
    } else {
        html.setAttribute('dir', 'ltr');
        html.setAttribute('lang', lang === 'en' ? 'en' : 'fr');
        menuBorder.style.direction = 'ltr';
    }

    // Update active button
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.remove('active');
        if (btn.getAttribute('data-lang') === lang) {
            btn.classList.add('active');
        }
    });
}

// Initialize on page load
document.addEventListener('DOMContentLoaded', () => {
    // Restore language from previous visit if available
    const savedLang = localStorage.getItem('cafeZizLang');
    if (savedLang) {
        setLanguage(savedLang);
    }

    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.addEventListener('click', () => {
            setLanguage(btn.getAttribute('data-lang'));
        });
    });
});
